@startuml 

skin rose 
  
:Admin: 

Admin --> (Realizar Cadastro no sistema) 
Admin --> (Gerenciar Animais)  

(Gerenciar Animais) <. (Atualizar informações dos Animais) : extends
(Realizar Cadastro no sistema) <. (Fazer Login no Sistema) : extends



@enduml 
